language: android
jdk:
- oraclejdk8
android:
  components:
  - platform-tools
  - tools
  - build-tools-25.0.0
  - android-25
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
  - addon-google_apis-google-19
script:
- "./gradlew build test :app:assembleAndroidTest"
before_install:
- openssl aes-256-cbc -K $encrypted_5baf7760a3e1_key -iv $encrypted_5baf7760a3e1_iv
  -in release.jks.enc -out release.jks -d
- export JAVA8_HOME=/usr/lib/jvm/java-8-oracle
- export JAVA_HOME=$JAVA8_HOME
env:
  global:
  - secure: UTlW06beLhLxR43J5756kEt05MC13sMg8GP9qsqm9w9PHyIDDDuqXm/FBc1ij6WrMOLEtc/oXCDeBeP1fRLJ0JCF+XhK0HYDtnhATrk40Q890SQr9G6KwKs0Z4rIxPmBpcdMTvSenAQy2IP9LYfyv9RZgw4862PZi5gGwXRvRlUNHbfCucV1CAPgoKjHj64sYj/MYsC4Z7wQK8Jtqj8mMI0Zybe24pA7MUJpq9uhyai+kH+YfZ0Kw+5Iz4IV462fCz9coLrI5shmRhIkwIReroplrA0JeTA7NqffSrU+TsM0j+ZsX0ApS2GEa1hyyU1wL6SyqpB2LswItSEQPD6aHBjEeZqzoSiTPur9/L3dSSe5zJO5pQAdgYDLF2H9NS1qfVN7TSyZQ9F5Ebvim+MFgENh6rnMQjr4etrVsO7yJkNyknWxPNp4UxncWU6mKMpifWQj4p+LrAyMBFTIayIhQ10BeeUS5NzpmZYRXcDHBm8ddkYH15l3Gi8SpQC/opibIoAzwnAUIW3afRbd0RXHpdFQ1ejYYxRE0mrW8oHfFm3mr1QqJtJQZrfjt1+ub2FKQzaPkrnx4URDXGti1RkDYNC7xRvgW1fFztKBI9KBrjDzFZEX3Mzu94cIRYb3jfkdHyuGfyEcqpt5o0u34j0dUIxW4RJ5T+7Ov4mR5eY5e0k=
  - secure: YA3foV8sNq0NsA84zub1WAjxEZyrwDruOeFqq8hKJzf2ufypWW341NRB+mnJx9M4HAdaQX0HLtYQOAlQxEVzT+lxmTd93/vgwwcDJdp7SqPn0Gf8bOBiB0xLJnrMELAVrP/K44Sa+4l0qt6jpj0ypO3lSu0uyXncZt8SeruT6vdxSl0MIOASkA1XZE/TmcQFqRnqCjPkLM99Hc0kj4Gbf3Tlxf5laYyBi1/iY47O+FtUWVlg6MDF9HcmcQBlR7f7Zy4tBY7d8eqVzkRMSrhLGVcUu0/RU8yxXWKqoxA3BmjPk6wSbk3HEGnw6iZC8hiqbKXMg2taxh1Cf9wvaZDJ8J+bNtA50fhbzY3as1Egjzy/mpRFs4wKrfmQT/m8CeNVnL5OvAMEZB0Bf5Hui9hHTOLtBCYVQjeyWGl1Fn9AVS71c0PUR1d7PL6aL3+W5u4OjisCkhRSilA0spDlJu18PAo+VJ2sA2KKqE26wnldjn/0M8Rx5NRyzBz2DU3oiGRhNZZ9hSZOM0ITAwCpWRR5TKzeWrTrycLpJXxzWnaddw4quzU75/Vsj8iGSdIJFuPcSKr6yK3e/12DH6GCYN/4SDd6uzyWMih0t+A9jq39MmrwtSbOfQApCDNKT3wk/Yr/NSPspdhWKZPfLGkwqtDWMXZITf7VGn2iVZlJHmLilk8=
  - secure: QUbdPczIQn4LsG6voY6YTD61njAHvPtw3wiPyTkLQRI+/MJ1Ruiu5ZG7slcQYb9zjaG0IHX0Kn1VbScR8MteGADGz+/0GU0J1VWBgnL2D+YjjV0cqJMvW5T3B40sU0plRQ24Jmxf1ayEDPoPmjn4rHp/b2SUA/niu1jd4yk7uR+55v5fYy8tVwXaUzLckc0Fnqqdjw/eG2AC1SJZAh5yz+sDUQB+9cx1y4+AC2zw+8DOcQckcDE96sQKcHAF4eESGkPUyNCVOv8DR96HSQMWcJKvxNONX52PrwE5UsHKX11fZ5VgrQfVLHwnc3OQJu65FfUglro00+guHjGv0Xif+sppi2u5IB+gu2SL9U6+81CE5R3HLBI1PaTmBfXtpQ+LP0ok1J8FSiE0mxTh7bCngQ6Gs3T+B8LzD1BX9+h/ONSc7N96JR3Ams8TT/PmlGjxaNeKWEP5wUHTLErZsncQrS3MwpkgtzqnM75iEa3Il51gYYkh/fKHNkikpPFb8pc/NCz7priujbw3/Yt8EfTv6mlxAr9t2HImquTMAxdVc4Fc5fQxji4QOwyisZz3VrSVu9b1XLttf9PLaxYirBa6ZmGdMP6vy/xeh4Mh8YdO7xAqOTn568PoG48XjaPhP5jXBFJaATcA5gXRgSGZI9eZFmLhOZugOgbq5C8nhaxFbg8=
